name: Report an Issue
description: Create a report about a bug or something that isn't working correctly in Freeform.
type: Problem
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please describe the issue that is happening.
      placeholder: Please elaborate as much as possible.
    validations:
      required: true
  - type: textarea
    id: errors-stack-trace
    attributes:
      label: Errors and Stack Trace (if available)
      description: If you are seeing any errors, please copy and paste those here (including the stack trace if possible). Be sure to check the Craft error logs to find more detailed errors.
      placeholder: This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: false
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: How can we reproduce this?
      description: Please describe how we can reproduce this issue. If possible, please simplify the issue as much as possible (while still seeing the issue) on your site.
      placeholder: Please elaborate as much as possible.
      value:  |
        1. 
        2. 
        3. 
    validations:
      required: true
  - type: dropdown
    id: freeform-edition
    attributes:
      label: Freeform Edition
      description: Which edition of Freeform are you currently using?
      options:
        - Pro
        - Lite
        - Express
    validations:
      required: true
  - type: input
    id: freeform-version
    attributes:
      label: Freeform Version
      description: Which version of Freeform are you currently using?
      placeholder: e.g. 5.3.1
    validations:
      required: true
  - type: input
    id: craft-version
    attributes:
      label: Craft Version
      description: Which version of Craft are you currently using?
      placeholder: e.g. 5.1.8
    validations:
      required: true
  - type: checkboxes
    id: when-started
    attributes:
      label: When did this issue start?
      description: Choose all that apply.
      options:
        - label: Unsure
        - label: Fresh install of Freeform
        - label: After upgrading from older Freeform version
        - label: After upgrading from older Craft version
        - label: After a change to hosting configuration
  - type: input
    id: previous-freeform-version
    attributes:
      label: Previous Freeform Version
      description: If this issue began after an update to Freeform, please let us know which version of Freeform you updated from.
      placeholder: e.g. 5.1.17
    validations:
      required: false
